### ISSUE TITLE
Socket InputStream not working for me

### ISSUE THREAD

**Issue by Amir-P** [cirosantilli/android-cheat#1]
Hi I've tried the code you've written for bi directional socket but it's not working. sending is ok at the first time but after reading from input stream (which returns nothing) socket is blocking and I can't send anything till I close the application and do that again. here is my code
```
try {
                    Socket socket = new Socket(DISPLAY_IP, DISPLAY_PORT);
                    OutputStream out = socket.getOutputStream();
                    out.write(params[0].getBytes());
                    InputStream in = socket.getInputStream();
                    byte buf[] = new byte[1024];
                    int nbytes;
                    StringBuilder sb = new StringBuilder();
                    while ((nbytes = in.read(buf)) != -1) {
                        sb.append(new String(buf, 0, nbytes));
                    }
                    socket.close();
                    Log.d("ss", sb.toString());
                } catch (Exception e) {
                    e.printStackTrace();
                }
```
and I'm using xSocket application for server connection on my laptop which returns automatically after receiving data

**Comment by cirosantilli** [comment]
Hi Amir, sorry but I don't have much time for this project now. But if you find out a solution, send me PR, and I will test and merge it :-)

**Comment by Amir-P** [comment]
I'm working on it for two days and it's not solving. If you have time please help me solve it it's so important @cirosantilli

**Comment by Amir-P** [comment]
I've found that the problem is with `input.read()` or `input.readLine()`. when I'm commenting these codes it's working great
